import '../../vant-css/base.css';
import '../../vant-css/field.css';
import '../../vant-css/popup.css';
import '../../vant-css/toast.css';
import '../../vant-css/dialog.css';
import '../../vant-css/picker.css';
import '../../vant-css/switch.css';
import '../../vant-css/switch-cell.css';
import '../../vant-css/address-edit.css';